apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-fe
  namespace: frontend
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    path: guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

